services:
  chroma-db:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./data/chromadb:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - document-chatbot-network

  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=doc-chatbot
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - document-chatbot-network


networks:
  document-chatbot-network:
    external: false
