"""ChatSession-User relationship.

Revision ID: 8e390a0e1449
Revises: 750061fde877
Create Date: 2023-10-09 08:27:34.075070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e390a0e1449'
down_revision: Union[str, None] = '750061fde877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('chat_sessions', 'user_id', server_default=None)
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
