"""CreatedAt column in chat sessions and prompts.

Revision ID: ab2139727011
Revises: 8e390a0e1449
Create Date: 2023-10-10 10:32:55.751997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2139727011'
down_revision: Union[str, None] = '8e390a0e1449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_prompts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'created_at')
    op.drop_column('chat_prompts', 'created_at')
    # ### end Alembic commands ###
